<?php

// === FILE: Modules/Delivery/Database/Migrations/2026_08_001_014_recreate_deliveries_table.php
//
//  Drops the existing (partially-created) deliveries table and
//  recreates it cleanly with all required columns.
//
//  Run:
//    php artisan migrate --path=modules/Delivery/Database/Migrations/2026_08_001_014_recreate_deliveries_table.php
// ================================================================

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    protected $connection = 'delivery';

    public function up(): void
    {
        // Drop the broken table (created by the failed previous migration)
        Schema::connection('delivery')->dropIfExists('deliveries');

        Schema::connection('delivery')->create('deliveries', function (Blueprint $table) {
            $table->char('id', 26)->primary();

            // ── Platform links ─────────────────────────────────
            $table->char('org_id', 26);
            $table->char('order_id', 26)->nullable();

            // ── Tracking ───────────────────────────────────────
            // TRK-YYYY-XXXX — auto-generated by Delivery::boot()
            $table->string('tracking_number', 20)->unique();

            // ── Transporter ────────────────────────────────────
            $table->string('transporter_name',  255);
            $table->string('transporter_phone', 20);
            $table->string('car_registration',  20);

            // ── Live GPS (pushed by driver app background service)
            $table->decimal('driver_latitude',  10, 7)->nullable();
            $table->decimal('driver_longitude', 10, 7)->nullable();
            $table->timestamp('location_updated_at')->nullable();

            // ── Cargo / fare ───────────────────────────────────
            $table->decimal('cargo_fare', 12, 2)->default(0);
            $table->boolean('fare_is_paid')->default(false);

            // URLs written after file upload to storage disk
            $table->string('parcel_image_path',  1000)->nullable();
            $table->string('waybill_image_path', 1000)->nullable();

            // ── Sender ─────────────────────────────────────────
            $table->string('sender_name',     255);
            $table->string('sender_location', 255);
            $table->string('sender_phone',    20)->nullable();

            // ── Receiver ───────────────────────────────────────
            $table->string('receiver_name',     255);
            $table->string('receiver_location', 255);
            $table->string('receiver_phone',    20)->nullable();

            // ── Status & lifecycle ─────────────────────────────
            // pending | in_transit | delivered | cancelled | failed
            $table->string('status', 50)->default('pending');
            $table->text('notes')->nullable();
            $table->timestamp('estimated_arrival')->nullable();
            $table->timestamp('delivered_at')->nullable();
            $table->timestamp('cancelled_at')->nullable();

            $table->timestamps();
            $table->softDeletes();

            // Indexes
            $table->index('org_id');
            $table->index('order_id');
            $table->index('tracking_number');
            $table->index('status');
        });

        // Status check constraint
        DB::connection('delivery')->statement("
            ALTER TABLE deliveries
            ADD CONSTRAINT chk_delivery_status
            CHECK (status IN ('pending','in_transit','delivered','cancelled','failed'))
        ");
    }

    public function down(): void
    {
        Schema::connection('delivery')->dropIfExists('deliveries');
    }
};