<?php
// === FILE: Modules/Delivery/Database/Migrations/2026_01_001_create_deliveries_table.php
//
//  New `deliveries` table in the `delivery` PostgreSQL schema.
//  tracking_number is auto-generated by the backend (TRK-YYYY-XXXX).
//  driver_latitude / driver_longitude are updated by PATCH .../location.
// ================================================================
 
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
 
return new class extends Migration
{
    protected $connection = 'delivery';
 
    public function up(): void
    {
        Schema::connection('delivery')->create('deliveries', function (Blueprint $table) {
            $table->char('id', 26)->primary();
 
            // ── Platform links ─────────────────────────────────
            $table->char('org_id', 26)->index();
            $table->char('order_id', 26)->nullable()->index();
 
            // ── Tracking ───────────────────────────────────────
            // e.g. TRK-2026-A3F9 — unique, human-readable, public
            $table->string('tracking_number', 20)->unique();
            $table->index('tracking_number');
 
            // ── Transporter ────────────────────────────────────
            $table->string('transporter_name',  255);
            $table->string('transporter_phone', 20);
            $table->string('car_registration',  20);
 
            // ── Live GPS ───────────────────────────────────────
            // Updated by driver app background service
            $table->decimal('driver_latitude',  10, 7)->nullable();
            $table->decimal('driver_longitude', 10, 7)->nullable();
            $table->timestamp('location_updated_at')->nullable();
            $table->index(['driver_latitude', 'driver_longitude']);
 
            // ── Cargo / fare ───────────────────────────────────
            $table->decimal('cargo_fare', 12, 2)->default(0);
            $table->boolean('fare_is_paid')->default(false);
            $table->string('parcel_image_path',  500)->nullable();
            $table->string('waybill_image_path', 500)->nullable();
 
            // ── Sender ─────────────────────────────────────────
            $table->string('sender_name',     255);
            $table->string('sender_location', 255);
            $table->string('sender_phone',    20)->nullable();
 
            // ── Receiver ───────────────────────────────────────
            $table->string('receiver_name',     255);
            $table->string('receiver_location', 255);
            $table->string('receiver_phone',    20)->nullable();
 
            // ── Status & lifecycle ─────────────────────────────
            $table->string('status', 50)->default('pending');
            // pending | in_transit | delivered | cancelled | failed
            $table->text('notes')->nullable();
            $table->timestamp('estimated_arrival')->nullable();
            $table->timestamp('delivered_at')->nullable();
            $table->timestamp('cancelled_at')->nullable();
 
            $table->timestamps();
            $table->softDeletes();
 
            $table->index('status');
            $table->index('org_id');
        });
 
        // Status check constraint
        \Illuminate\Support\Facades\DB::connection('delivery')->statement("
            ALTER TABLE deliveries
            ADD CONSTRAINT chk_delivery_status
            CHECK (status IN ('pending','in_transit','delivered','cancelled','failed'))
        ");
    }
 
    public function down(): void
    {
        Schema::connection('delivery')->dropIfExists('deliveries');
    }
};